api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
web_app:
    resource: "@AppBundle/Controller/Web"
    type:     annotation
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"